export const SET_QUIZ_TEMPLATES = "SET_QUIZ_TEMPLATES";
export const REMOVE_QUIZ_TEMPLATE = "REMOVE_QUIZ_TEMPLATE";
export const APPEND_QUIZ_TEMPLATE = "APPEND_QUIZ_TEMPLATE";

export const SET_QUESTION_TEMPLATES = "SET_QUESTION_TEMPLATES";
export const REMOVE_QUESTION_TEMPLATE = "REMOVE_QUESTION_TEMPLATE";
export const APPEND_QUESTION_TEMPLATE = "APPEND_QUESTION_TEMPLATE";
export const OPEN_QUESTION_TEMPLATE_VIEW = "OPEN_QUESTION_TEMPLATE_VIEW";
export const SET_QUESTION_TEMPLATE_CREATE = "SET_QUESTION_TEMPLATE_CREATE";

export const SET_QUIZZES = "SET_QUIZZES";
export const OPEN_QUIZ_VIEW = "OPEN_QUIZ_VIEW";
export const SET_QUESTION_SCORE = "SET_QUESTION_SCORE";

export const SET_VIEWED_USER = "SET_VIEWED_USER";
export const SET_USERS = "SET_USERS";
export const APPEND_USER = "APPEND_USER";
export const SET_USERS_ONLINE = "SET_USERS_ONLINE";
export const SET_USER_CREATE = "SET_USER_CREATE";

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_STAT_AVG_RESULT = 'SET_STAT_AVG_RESULT';
export const SET_STAT_AVG_TIME = 'SET_STAT_AVG_TIME';
export const SET_STAT_BEST_RESULT = 'SET_STAT_BEST_RESULT';
export const SET_STAT_TOTAL_ATTEMPTS = 'SET_STAT_TOTAL_ATTEMPTS';
export const SET_STAT_TOTAL_INCOMPLETE = 'SET_STAT_TOTAL_INCOMPLETE';
