export const SET_QUIZ_TEMPLATES = "SET_QUIZ_TEMPLATES";
export const REMOVE_QUIZ_TEMPLATE = "REMOVE_QUIZ_TEMPLATE";
export const APPEND_QUIZ_TEMPLATE = "APPEND_QUIZ_TEMPLATE";
export const SET_QUIZZES = "SET_QUIZZES";
