export const SET_QUIZ_TEMPLATES = "SET_QUIZ_TEMPLATES";
export const REMOVE_QUIZ_TEMPLATE = "REMOVE_QUIZ_TEMPLATE";
export const APPEND_QUIZ_TEMPLATE = "APPEND_QUIZ_TEMPLATE";

export const SET_QUESTION_TEMPLATES = "SET_QUESTION_TEMPLATES";
export const REMOVE_QUESTION_TEMPLATE = "REMOVE_QUESTION_TEMPLATE";
export const APPEND_QUESTION_TEMPLATE = "APPEND_QUESTION_TEMPLATE";

export const SET_QUIZZES = "SET_QUIZZES";

export const SET_VIEWED_USER = "SET_VIEWED_USER";
export const SET_USERS = "SET_USERS";
export const SET_USERS_ONLINE = "SET_USERS_ONLINE";
