# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:3030/login
Accept: application/json

###

POST http://localhost:3030/login_check
Content-Type: application/x-www-form-urlencoded

username=Calin&password=123

###

GET http://localhost:3030/
Accept: application/json

###