// Code generated by entc, DO NOT EDIT.

package quiz

import (
	"github.com/calinpristavu/quizzer/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldID), id))
		},
	)
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldID), id))
		},
	)
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldID), id))
		},
	)
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(ids) == 0 {
				s.Where(sql.False())
				return
			}
			v := make([]interface{}, len(ids))
			for i := range v {
				v[i] = ids[i]
			}
			s.Where(sql.In(s.C(FieldID), v...))
		},
	)
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(ids) == 0 {
				s.Where(sql.False())
				return
			}
			v := make([]interface{}, len(ids))
			for i := range v {
				v[i] = ids[i]
			}
			s.Where(sql.NotIn(s.C(FieldID), v...))
		},
	)
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.GT(s.C(FieldID), id))
		},
	)
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.GTE(s.C(FieldID), id))
		},
	)
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.LT(s.C(FieldID), id))
		},
	)
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.LTE(s.C(FieldID), id))
		},
	)
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldName), v))
		},
	)
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldActive), v))
		},
	)
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v uint) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldScore), v))
		},
	)
}

// Corrected applies equality check predicate on the "corrected" field. It's identical to CorrectedEQ.
func Corrected(v bool) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldCorrected), v))
		},
	)
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldName), v))
		},
	)
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldName), v))
		},
	)
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Quiz {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Quiz(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.In(s.C(FieldName), v...))
		},
	)
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Quiz {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Quiz(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.NotIn(s.C(FieldName), v...))
		},
	)
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.GT(s.C(FieldName), v))
		},
	)
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.GTE(s.C(FieldName), v))
		},
	)
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.LT(s.C(FieldName), v))
		},
	)
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.LTE(s.C(FieldName), v))
		},
	)
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.Contains(s.C(FieldName), v))
		},
	)
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.HasPrefix(s.C(FieldName), v))
		},
	)
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.HasSuffix(s.C(FieldName), v))
		},
	)
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EqualFold(s.C(FieldName), v))
		},
	)
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.ContainsFold(s.C(FieldName), v))
		},
	)
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldActive), v))
		},
	)
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldActive), v))
		},
	)
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v uint) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldScore), v))
		},
	)
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v uint) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldScore), v))
		},
	)
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...uint) predicate.Quiz {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Quiz(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.In(s.C(FieldScore), v...))
		},
	)
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...uint) predicate.Quiz {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Quiz(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.NotIn(s.C(FieldScore), v...))
		},
	)
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v uint) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.GT(s.C(FieldScore), v))
		},
	)
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v uint) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.GTE(s.C(FieldScore), v))
		},
	)
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v uint) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.LT(s.C(FieldScore), v))
		},
	)
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v uint) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.LTE(s.C(FieldScore), v))
		},
	)
}

// CorrectedEQ applies the EQ predicate on the "corrected" field.
func CorrectedEQ(v bool) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldCorrected), v))
		},
	)
}

// CorrectedNEQ applies the NEQ predicate on the "corrected" field.
func CorrectedNEQ(v bool) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldCorrected), v))
		},
	)
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Quiz) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			for _, p := range predicates {
				p(s)
			}
		},
	)
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Quiz) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			for i, p := range predicates {
				if i > 0 {
					s.Or()
				}
				p(s)
			}
		},
	)
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Quiz) predicate.Quiz {
	return predicate.Quiz(
		func(s *sql.Selector) {
			p(s.Not())
		},
	)
}
