// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"log"

	"github.com/facebookincubator/ent/dialect/sql"
)

// dsn for the database. In order to run the tests locally, run the following command:
//
//	 ENT_INTEGRATION_ENDPOINT="root:pass@tcp(localhost:3306)/test?parseTime=True" go test -v
//
var dsn string

func ExampleQuiz() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the quiz's edges.

	// create quiz vertex with its edges.
	q := client.Quiz.
		Create().
		SetName("string").
		SetActive(true).
		SetScore(1).
		SetCorrected(true).
		SaveX(ctx)
	log.Println("quiz created:", q)

	// query edges.

	// Output:
}
func ExampleUser() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the user's edges.

	// create user vertex with its edges.
	u := client.User.
		Create().
		SetUsername("string").
		SetPassword("string").
		SetRoleID(1).
		SetIsEnabled(true).
		SetShouldStartID(1).
		SetComments("string").
		SetRecruiteeID(1).
		SaveX(ctx)
	log.Println("user created:", u)

	// query edges.

	// Output:
}
