// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Quiz is the predicate function for quiz builders.
type Quiz func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
